/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scoreboard;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author DeeJay
 */
public class Scoreboard extends javax.swing.JFrame {
    
    private int quarter, homeScore, visitorScore, remainingTime;
    private boolean remainingTimeIsPaused;

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        this.quarter = 0;
        this.homeScore = 0;
        this.visitorScore = 0;
        this.remainingTime = 720000;
        this.remainingTimeIsPaused = true;
        
        Thread currentTimeClock = new Thread(new CurrentTimeClock());
        currentTimeClock.start();
        
        Thread remainingTimeClock = new Thread(new RemainingTimeCounter());
        remainingTimeClock.start();
        
        initComponents();
    }
    
    private void handleRemainingTimeResume() {
        this.setRemainingTimeIsPaused(false);
    }
    
    private void handleRemainingTimePause() {
        this.setRemainingTimeIsPaused(true);
    }
    
    private void handleRemainingTimeReset() {
        this.setRemainingTimeIsPaused(true);
        this.setRemainingTime(720000);
        this.remainingTimeValue.setText(this.msToMmSsString(this.remainingTime));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visitorLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        quarterPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        currentQuarter = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        homeScorePanel = new javax.swing.JPanel();
        homeScorePlus = new javax.swing.JButton();
        homeScoreMinus = new javax.swing.JButton();
        homeScoreLabel = new javax.swing.JLabel();
        visitorScorePanel = new javax.swing.JPanel();
        visitorScorePlus = new javax.swing.JButton();
        visitorScoreMinus = new javax.swing.JButton();
        visitorScoreLabel = new javax.swing.JLabel();
        currentTimePanel = new javax.swing.JPanel();
        currentTimePanelLabel = new javax.swing.JLabel();
        currentTimeValue = new javax.swing.JLabel();
        remainingTimePanel = new javax.swing.JPanel();
        remainingTimePanelLabel = new javax.swing.JLabel();
        remainingTimeValue = new javax.swing.JLabel();
        remainingTimeStop = new javax.swing.JButton();
        remainingTimeResume = new javax.swing.JButton();
        remainingTimeReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scoreboard");
        setBackground(new java.awt.Color(255, 255, 255));

        visitorLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        visitorLabel.setText("Visitor");

        homeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeLabel.setText("Home");

        label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label.setText("Quarter");

        currentQuarter.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        currentQuarter.setForeground(new java.awt.Color(102, 0, 204));
        currentQuarter.setText("0");
        currentQuarter.setOpaque(true);

        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quarterPanelLayout = new javax.swing.GroupLayout(quarterPanel);
        quarterPanel.setLayout(quarterPanelLayout);
        quarterPanelLayout.setHorizontalGroup(
            quarterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quarterPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(label)
                .addGroup(quarterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(quarterPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(minusButton))
                    .addGroup(quarterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(currentQuarter)
                        .addGap(12, 12, 12)
                        .addComponent(plusButton)))
                .addGap(19, 19, 19))
        );
        quarterPanelLayout.setVerticalGroup(
            quarterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quarterPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(quarterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(quarterPanelLayout.createSequentialGroup()
                        .addComponent(plusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusButton))
                    .addComponent(currentQuarter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        homeScorePlus.setText("+");
        homeScorePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeScorePlusActionPerformed(evt);
            }
        });

        homeScoreMinus.setText("-");
        homeScoreMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeScoreMinusActionPerformed(evt);
            }
        });

        homeScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        homeScoreLabel.setText("0");

        javax.swing.GroupLayout homeScorePanelLayout = new javax.swing.GroupLayout(homeScorePanel);
        homeScorePanel.setLayout(homeScorePanelLayout);
        homeScorePanelLayout.setHorizontalGroup(
            homeScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeScorePlus)
                    .addComponent(homeScoreMinus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeScoreLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        homeScorePanelLayout.setVerticalGroup(
            homeScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScorePanelLayout.createSequentialGroup()
                .addGroup(homeScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homeScorePanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(homeScorePlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeScoreMinus))
                    .addGroup(homeScorePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeScoreLabel)))
                .addGap(41, 41, 41))
        );

        visitorScorePlus.setText("+");
        visitorScorePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorScorePlusActionPerformed(evt);
            }
        });

        visitorScoreMinus.setText("-");
        visitorScoreMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorScoreMinusActionPerformed(evt);
            }
        });

        visitorScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        visitorScoreLabel.setText("0");

        javax.swing.GroupLayout visitorScorePanelLayout = new javax.swing.GroupLayout(visitorScorePanel);
        visitorScorePanel.setLayout(visitorScorePanelLayout);
        visitorScorePanelLayout.setHorizontalGroup(
            visitorScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitorScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visitorScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitorScorePlus)
                    .addComponent(visitorScoreMinus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visitorScoreLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        visitorScorePanelLayout.setVerticalGroup(
            visitorScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visitorScorePanelLayout.createSequentialGroup()
                .addGroup(visitorScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(visitorScorePanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(visitorScorePlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visitorScoreMinus))
                    .addGroup(visitorScorePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(visitorScoreLabel)))
                .addGap(41, 41, 41))
        );

        currentTimePanel.setBackground(new java.awt.Color(0, 0, 0));

        currentTimePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentTimePanelLabel.setText("Current Time");

        currentTimeValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentTimeValue.setForeground(new java.awt.Color(255, 255, 255));
        currentTimeValue.setText("hh:mm:ss");

        javax.swing.GroupLayout currentTimePanelLayout = new javax.swing.GroupLayout(currentTimePanel);
        currentTimePanel.setLayout(currentTimePanelLayout);
        currentTimePanelLayout.setHorizontalGroup(
            currentTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentTimePanelLabel)
                .addGap(16, 16, 16)
                .addComponent(currentTimeValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currentTimePanelLayout.setVerticalGroup(
            currentTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentTimePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(currentTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentTimePanelLabel)
                    .addComponent(currentTimeValue))
                .addContainerGap())
        );

        remainingTimePanel.setBackground(new java.awt.Color(204, 204, 204));

        remainingTimePanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        remainingTimePanelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remainingTimePanelLabel.setText("Remaining Time");

        remainingTimeValue.setBackground(new java.awt.Color(0, 0, 0));
        remainingTimeValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        remainingTimeValue.setText("12:00");

        remainingTimeStop.setText("Stop");
        remainingTimeStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingTimeStopActionPerformed(evt);
            }
        });

        remainingTimeResume.setText("Resume");
        remainingTimeResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingTimeResumeActionPerformed(evt);
            }
        });

        remainingTimeReset.setText("Reset");
        remainingTimeReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingTimeResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout remainingTimePanelLayout = new javax.swing.GroupLayout(remainingTimePanel);
        remainingTimePanel.setLayout(remainingTimePanelLayout);
        remainingTimePanelLayout.setHorizontalGroup(
            remainingTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remainingTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remainingTimePanelLabel)
                .addGap(42, 42, 42)
                .addComponent(remainingTimeValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(remainingTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remainingTimeStop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remainingTimeResume, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remainingTimeReset, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
        remainingTimePanelLayout.setVerticalGroup(
            remainingTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remainingTimePanelLayout.createSequentialGroup()
                .addGroup(remainingTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remainingTimePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(remainingTimePanelLabel))
                    .addGroup(remainingTimePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(remainingTimeStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remainingTimeResume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remainingTimeReset))
                    .addGroup(remainingTimePanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(remainingTimeValue)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeScorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quarterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitorLabel)
                    .addComponent(visitorScorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remainingTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitorLabel)
                    .addComponent(homeLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeScorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(visitorScorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(quarterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(remainingTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        if (this.quarter > 0) {
            this.quarter--;
            currentQuarter.setText(String.valueOf(this.quarter));
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        if (this.quarter < 4) {
            this.quarter++;
            currentQuarter.setText(String.valueOf(this.quarter));
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void homeScoreMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeScoreMinusActionPerformed
        if (this.homeScore > 0) {
            this.homeScore--;
            homeScoreLabel.setText(String.valueOf(this.homeScore));
        }
    }//GEN-LAST:event_homeScoreMinusActionPerformed

    private void homeScorePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeScorePlusActionPerformed
        this.homeScore++;
        homeScoreLabel.setText(String.valueOf(this.homeScore));
    }//GEN-LAST:event_homeScorePlusActionPerformed

    private void visitorScorePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorScorePlusActionPerformed
        this.visitorScore++;
        visitorScoreLabel.setText(String.valueOf(this.visitorScore));
    }//GEN-LAST:event_visitorScorePlusActionPerformed

    private void visitorScoreMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorScoreMinusActionPerformed
        if (this.visitorScore > 0) {
            this.visitorScore--;
            visitorScoreLabel.setText(String.valueOf(this.visitorScore));
        }
    }//GEN-LAST:event_visitorScoreMinusActionPerformed

    private void remainingTimeStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingTimeStopActionPerformed
        this.handleRemainingTimePause();
    }//GEN-LAST:event_remainingTimeStopActionPerformed

    private void remainingTimeResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingTimeResumeActionPerformed
        this.handleRemainingTimeResume();
    }//GEN-LAST:event_remainingTimeResumeActionPerformed

    private void remainingTimeResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingTimeResetActionPerformed
        this.handleRemainingTimeReset();
    }//GEN-LAST:event_remainingTimeResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scoreboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentQuarter;
    private javax.swing.JPanel currentTimePanel;
    private javax.swing.JLabel currentTimePanelLabel;
    private javax.swing.JLabel currentTimeValue;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeScoreLabel;
    private javax.swing.JButton homeScoreMinus;
    private javax.swing.JPanel homeScorePanel;
    private javax.swing.JButton homeScorePlus;
    private javax.swing.JLabel label;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JPanel quarterPanel;
    private javax.swing.JPanel remainingTimePanel;
    private javax.swing.JLabel remainingTimePanelLabel;
    private javax.swing.JButton remainingTimeReset;
    private javax.swing.JButton remainingTimeResume;
    private javax.swing.JButton remainingTimeStop;
    private javax.swing.JLabel remainingTimeValue;
    private javax.swing.JLabel visitorLabel;
    private javax.swing.JLabel visitorScoreLabel;
    private javax.swing.JButton visitorScoreMinus;
    private javax.swing.JPanel visitorScorePanel;
    private javax.swing.JButton visitorScorePlus;
    // End of variables declaration//GEN-END:variables

    class CurrentTimeClock implements Runnable {
        
        public void run() {
            while (true) {
                updateCurrentTime();
                
                try {
                    Thread.sleep(1000);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    System.exit(1);
                }
                
            }
        }
        
        private void updateCurrentTime() {
            SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
            String currentTime = dateFormat.format(new Date());
            currentTimeValue.setText(currentTime);
        }
    }
    
    public void setRemainingTimeIsPaused(boolean b) {
        this.remainingTimeIsPaused = b;
    }
    
    public void setRemainingTime(int ms) {
        if (ms >= 0) {
            this.remainingTime = ms;
        } else {
            this.remainingTime = 0;
            setRemainingTimeIsPaused(true);
        }
    }
    
    class RemainingTimeCounter implements Runnable {
        
        public void run() {
            while (true) {
                while (!remainingTimeIsPaused) {
                    remainingTimeValue.setText(msToMmSsString(remainingTime));
                    
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        System.exit(1);
                    }
                    
                    setRemainingTime(remainingTime - 1000);
                }
                try {
                    Thread.sleep(1);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    System.exit(1);
                }
            }
            
        }
    }
    
    private String msToMmSsString(int ms) {
        int seconds = ms / 1000;
        int ss = seconds % 60;
        int mm = (seconds / 60);
        return String.format("%02d:%02d", mm, ss);
    }
}
