POST http://localhost:3000/contact
Content-Type: application/json

{
    "student_id": "22101295",
    "name": "Christian de Jesus",
    "age": "20",
    "contact": "09455722882",
    "course": "BS PS"
}